### ISSUE TITLE
Set watched folder via an expression

### ISSUE THREAD

**Issue by evdheuvel70** [fatoldsun00/node-red-contrib-watchdirectory#2]
I'm deploying my flows on multiple NR instances. I have a startup (inject) flow that prepares global properties on deploying the flow. As flow developer I want to set the Watched directory based on an Expression and/or from a global property so that I do not need to each change node-red-contrib-watchdirectory node manually on each instance.

For example:
$globalContext('workspace') & '\\in'

**Comment by lost-bits** [comment]
Maybe the better way would be having a ingest node setting the parameters? (like the original watch)

**Comment by RitaSghe** [comment]
Hi,
no news?
Also for me it would be important to set with function the folder .....
